# Generated by Django 4.0.3 on 2022-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
