# Generated by Django 4.0.3 on 2022-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
