# Generated by Django 4.0.3 on 2022-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_items_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
